# Generated by Django 4.2.7 on 2023-11-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircraft",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNV", "Unavailable"),
                    ("MTN", "Maintenance"),
                    ("AVL", "Available"),
                    ("RES", "Reserved"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="crew",
            name="status",
            field=models.CharField(
                choices=[
                    ("REG", "Registered"),
                    ("UNV", "Unavailable"),
                    ("AVL", "Available"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="type",
            field=models.CharField(
                choices=[("BUS", "Business"), ("ORD", "Oridnary"), ("CMF", "Comfort")],
                max_length=3,
            ),
        ),
    ]
