# Generated by Django 4.2.7 on 2023-11-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_aircraft_status_alter_crew_status_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Fight",
            new_name="Flight",
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNV", "Unavailable"),
                    ("RES", "Reserved"),
                    ("MTN", "Maintenance"),
                    ("AVL", "Available"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="crew",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNV", "Unavailable"),
                    ("REG", "Registered"),
                    ("AVL", "Available"),
                ],
                max_length=3,
            ),
        ),
    ]
