# Generated by Django 4.2.7 on 2023-11-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_rename_fight_flight_alter_aircraft_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircraft",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNV", "Unavailable"),
                    ("AVL", "Available"),
                    ("RES", "Reserved"),
                    ("MTN", "Maintenance"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="type",
            field=models.CharField(
                choices=[("CMF", "Comfort"), ("ORD", "Oridnary"), ("BUS", "Business")],
                max_length=3,
            ),
        ),
    ]
