
# Crews
CREW_NUMBER = 10 #def 100

# Airplane 
NUM_AIRPLANES = 10 #def 100

# Flights
NUM_DAYS = 30
NUM_FLIGHTS_PER_DAY = 1000 #def 5

# FlightCrews
CREW_PER_FLIGHT = 2 #def 5

# PASSENGERS PER FLIGHT
PASSENGERS_PER_FLIGHT = 2 #def 10

# USERS
USERS_TO_GENERATE = 10